# Startup: mkdocs serve
plugins:
  - search

extra_css:
  - stylesheets/extra.css

site_name: Engineering bible
site_url: https://adrem-engineering-bible.com

theme:
  name: material

  font:
    text: Roboto

  logo: assets/AdRem_name+logo.png
  favicon: assets/AdRem_logo_white.png

  # # add navigation footer to the site
  # features:
  #   - navigation.footer

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    
    - toc.follow

    - search.suggest

markdown_extensions:
  # Enable code hightlighting and line numbers
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Enable content tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Enable admonitions
  - admonition
  - pymdownx.details

  # Add aditional icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - attr_list

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/advanced-design-of-recycling-machines/posts/?feedView=all
      name: Ad Rem on LinkedIn

copyright: ©2026 Ad Rem

nav:
  - Design bible:
    - Design-bible/index.md 
    - Design-bible/Admonitions.md
    - Diagram examples:
      - Design-bible/Test submap/index.md
      - Design-bible/Test submap/test1.md
      - Design-bible/Test submap/test2.md
  - Calculators:
    - Calculators/index.md
    - Calculators/Content-tabs-with-code.md
  - Standards:
    - Standards/index.md