# Startup: mkdocs serve
plugins:
  - search

extra_css:
  - stylesheets/extra.css

site_name: Engineering playbook
site_url: https://adrem-engineering-playbook.com

theme:
  name: material

  font:
    text: Roboto

  logo: assets/AdRem_name+logo.png
  favicon: assets/AdRem_logo_white.png

  # # add navigation footer to the site
  # features:
  #   - navigation.footer

  palette:
    # Only light mode
    scheme: default
    primary: custom

    # # Switch between automatic, light and dark mode
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode
    #   primary: custom

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to system preference
    #   primary: custom
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    
    - toc.follow

    - search.suggest

markdown_extensions:
  # Enable code hightlighting and line numbers
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Enable content tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Enable admonitions
  - admonition
  - pymdownx.details

  # Add aditional icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - attr_list

  # Enable data tables
  - tables

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/advanced-design-of-recycling-machines/posts/?feedView=all
      name: Ad Rem on LinkedIn

copyright: ©2026 Ad Rem

nav:
  - Design playbook:
    - Design-playbook/index.md
    - Design-playbook/Guidelines-and-structure.md
    - Design-playbook/Corrupt-parts.md
    - Design-playbook/Bolt-connections.md
    - Design-playbook/Hole-slot-dimensions.md
    - Design-playbook/Structure-and-platform-information.md
    - Design-playbook/Mounting-machine-parts-on-structures.md
    - Design-playbook/Sheet-metal-information.md
    - Design-playbook/Info-LaserCut.md
    - Design-playbook/Info-Saw-Work-SW.md
    - Design-playbook/Database-agreements.md
    - Design-playbook/Welding.md
    - Design-playbook/Platforms.md
    - Design-playbook/Geared-motors-Siemens.md
    - Design-playbook/Classification.md
    - Design-playbook/Norms-on-electrics.md
  - Calculators:
    - Calculators/index.md
    - Calculators/Content-tabs-with-code.md
  - Standards:
    - Standards/index.md